name: Import SSC SAST Results (SARIF format) into GitHub Code Scanning Alerts
on: 
 workflow_dispatch:
 push:
  tags:
   - '*'
      
jobs:                                                  
  Export-FoD-To-GitHub:
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
       - uses: actions/checkout@v3
       - name: Setup Java
         uses: actions/setup-java@v3
         with:
          java-version: 17
          distribution: 'zulu'
       - name: Setting FQDN address
         run: |
              export RUNNER_ALLOW_RUNASROOT="1"
              export AGENT_ALLOW_RUNASROOT="1"
              sudo echo "54.196.18.172 fortify.cyberxdemo.com" | sudo tee -a /etc/hosts
              cat /etc/hosts
       # Pull SAST issues from SSC and generate GitHub-optimized SARIF output
       - name: Export Results to GitHub-optimized SARIF
         uses: fortify/gha-export-vulnerabilities@v1
         with:
          ssc_base_url: ${{ secrets.SSC_BASE_URL }}
          #ssc_auth_token: ${{ secrets.SSC_AUTHTOKEN_DECODED }}
          ssc_user: ${{ secrets.SSC_USER }}
          ssc_password: ${{ secrets.SSC_PWD }}
          ssc_version_name: "My Application:1.0"

       # Import Fortify SAST results to GitHub Security Code Scanning
       - name: Import Results
         uses: github/codeql-action/upload-sarif@v2
         with:
          sarif_file: ./gh-fortify-sast.sarif
