name: Import SSC SAST Results (SARIF format) into GitHub Code Scanning Alerts
on: 
 workflow_dispatch:
 push:
  tags:
   - '*'
      
jobs:                                                  
  Export-FoD-To-GitHub:
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
       - uses: actions/checkout@v3
       # Pull SAST issues from SSC and generate GitHub-optimized SARIF output
       - name: Export Results to GitHub-optimized SARIF
         uses: fortify/gha-export-vulnerabilities@v1
         with:
          ssc_base_url: ${{ secrets.SSC_BASE_URL }}
          ssc_auth_token: ${{ secrets.SSC_AUTHTOKEN_DECODED }}
          ssc_version_id: ${{ secrets.SSC_VERSION_ID }}

       # Import Fortify SAST results to GitHub Security Code Scanning
       - name: Import Results
         uses: github/codeql-action/upload-sarif@v2
         with:
          sarif_file: ./gh-fortify-sast.sarif
