name: Import SSC SAST Results (GitLab format) into GitLab Code Scanning Alerts
on: 
 workflow_dispatch:
 push:
  tags:
   - '*'
      
jobs:                                                  
  Export-SSC-To-GitHub:
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
       - uses: actions/checkout@v3
       # Pull SAST issues from SSC and generate GitLab-jaon output
       - name: Export Results
         uses: fortify/gha-export-vulnerabilities@v1
         with:
          export_config: /config/SSCToGitLab.yml
          ssc_base_url: "http://3.95.208.58:8180/ssc"
          #ssc_auth_token: ${{ secrets.SSC_AUTHTOKEN_DECODED }}
          ssc_user: ${{secrets.SSC_USER}}
          ssc_password: ${{secrets.SSC_PWD}}
          ssc_version_name: "My Application:1.0"
       # Import Fortify SAST results to GitLab Security Code Scanning
       - uses: actions/upload-artifact@v3
         if: always()
         with:
          name: json-files
          path: '**/*.json'
