name: Import SSC SAST Results (GitLab format) into GitLab Code Scanning Alerts
on: 
 workflow_dispatch:
 push:
  tags:
   - '*'
      
jobs:                                                  
  Export-SSC-To-GitHub:
    runs-on: ubuntu-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
       - uses: actions/checkout@v3
       # Pull SAST issues from SSC and generate GitLab-jaon output
       - name: Export Results
         uses: fortify/gha-export-vulnerabilities@v1
         with:
          export_config: ${{github.workspace}}/MyCustomExportConfig_GITLAB_Export.yml
          //export_target: GitLab
          ssc_base_url: "http://54.144.210.118:8180/ssc"
          #ssc_auth_token: ${{ secrets.SSC_AUTHTOKEN_DECODED }}
          ssc_user: ${{secrets.SSC_USER}}
          ssc_password: ${{secrets.SSC_PWD}}
          ssc_version_name: "My Application:1.0"
     # Import Fortify SAST results to GitLab Security Code Scanning
       - uses: actions/upload-artifact@v3
         if: always()
         with:
          name: json-files
          path: '*.json'
       - name: Publish report
         id: import-scan
         uses: ivanamat/defectdojo-import-scan@v1
         with:
          token: "548afd6fab3bea9794a41b31da0e9404f733e222"
          defectdojo_url: "https://demo.defectdojo.org"
          file: gl-fortify-sast.json
          scan_type: GitLab SAST Report
          product_name: "TestApp"
       - name: Show response
         run: |
          set -e
          printf '%s\n' '${{ steps.import-scan.outputs.response }}'
